version: '3.9'

services:
  app:
    build: .
    container_name: spring_app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/javaspringdb
      SPRING_DATASOURCE_USERNAME: javaspring
      SPRING_DATASOURCE_PASSWORD: javaspring
    networks:
      - spring-net

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: javaspringdb
      POSTGRES_USER: javaspring
      POSTGRES_PASSWORD: javaspring
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - spring-net

volumes:
  postgres_data:

networks:
  spring-net: